# Generated by Django 5.1.4 on 2025-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book'), ('can_view', 'Can view book'), ('can_create', 'Can create book'), ('can_edit', 'Can edit book')]},
        ),
    ]
