# Generated by Django 5.1.4 on 2025-08-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view user'), ('can_create', 'Can create user'), ('can_edit', 'Can edit user'), ('can_delete', 'Can delete user')]},
        ),
    ]
